### ISSUE TITLE
Refactor the Navbar component 

### ISSUE THREAD

**Issue by AleksandarIvezic** [danmainah/vacations-booking-front-end#53]
Is there a better way to do this? Perhaps consider possible reusability for nav links

_Originally posted by @mcrd25 in https://github.com/danmainah/vacations-booking-front-end/pull/51#discussion_r756227173_

**Comment by themonster2015** [comment]
We just created a [PR](https://github.com/danmainah/vacations-booking-front-end/pull/56) for this
